#!/usr/bin/env bash

# cfg xTor-linux

echo "[CFG] INIT => PROCCESS PLEASE WAIT..."

# remove fonts

sudo rm -Rf ./fonts/*
sudo rmdir ./fonts

# remove fonts

sudo rm -Rf ./TorBrowser/Data/fontconfig/*
sudo rmdir ./TorBrowser/Data/fontconfig

# remove torrc
sudo rm -Rf ./TorBrowser/Data/Tor/torrc
sudo rm -Rf ./TorBrowser/Data/Tor/torrc.orig.1

echo "
# torrc-defaults for Tor Browser
#
# DO NOT EDIT THIS FILE
#
# This file is distributed with Tor Browser and SHOULD NOT be modified (it
# may be overwritten during the next Tor Browser update). To customize your
# Tor configuration, shut down Tor Browser and edit the torrc file.
#
# If non-zero, try to write to disk less frequently than we would otherwise.

HiddenServiceDir ./TorBrowser/Data/Tor/hidden_service/
HiddenServicePort 80 127.0.0.1:80
HiddenServiceVersion 3

### Производительность ###

AvoidDiskWrites 1
HardwareAccel 1
NumCPUs 2
CircuitBuildTimeout 10
KeepalivePeriod 60
NewCircuitPeriod 40
NumEntryGuards 8
MaxCircuitDirtiness 600
MaxClientCircuitsPending 48
UseEntryGuards 1
EnforceDistinctSubnets 1
ClientRejectInternalAddresses 1

#cfg HTTP PROCCESS TOR
TransPort 9140 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr
ExitPolicy accept *:53        # DNS
ExitPolicy accept *:80-81     # HTTP 
ExitPolicy accept *:443       # HTTPS
ExitPolicy reject *:*

# Where to send logging messages.  Format is minSeverity[-maxSeverity]
# (stderr|stdout|syslog|file FILENAME).
Log notice stdout
CookieAuthentication 1
DormantCanceledByStartup 1
ClientTransportPlugin meek_lite,obfs2,obfs3,obfs4,scramblesuit,webtunnel exec ./TorBrowser/Tor/PluggableTransports/lyrebird
ClientTransportPlugin snowflake exec ./TorBrowser/Tor/PluggableTransports/lyrebird
ClientTransportPlugin conjure exec ./TorBrowser/Tor/PluggableTransports/conjure-client -registerURL https://registration.refraction.network/api

" > ./TorBrowser/Data/Tor/torrc-defaults

echo "[CFG] INIT => SUCCESS :)"

echo "[CFG MAIN] INIT => PROCCESS PLEASE WAIT..."

cat ./.cfg > ./start-tor-browser

echo "[CFG MAIN] INIT => SUCCESS :)"

./start-tor-browser
